function [out1,out2] = fwd_cartesian(thetaL,thetaR)
%FWD_CARTESIAN
%    [OUT1,OUT2] = FWD_CARTESIAN(thetaL,thetaR)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Dec-2022 13:32:20

t2 = cos(thetaL);
t3 = cos(thetaR);
t4 = sin(thetaL);
t5 = sin(thetaR);
t10 = pi./2.0;
t6 = real(t2);
t7 = real(t3);
t8 = real(t4);
t9 = real(t5);
t11 = t2./8.0;
t12 = t3./8.0;
t13 = t4./8.0;
t14 = t5./8.0;
t15 = -t11;
t16 = -t14;
t17 = t6./1.6e+1;
t18 = t7./1.6e+1;
t21 = t8.*6.25e-2i;
t22 = t9.*6.25e-2i;
t19 = -t17;
t20 = -t18;
t23 = -t21;
t24 = -t22;
t25 = t13+t16;
t27 = t12+t15+1.0./1.0e+1;
t26 = t25.^2;
t28 = t27.^2;
t29 = t26+t28;
t30 = 1.0./t29;
t31 = t30./4.0;
t32 = t31-1.0;
t33 = sqrt(t32);
t34 = t25.*t33;
t36 = t27.*t33;
t35 = real(t34);
t38 = real(t36);
t37 = t35./2.0;
t40 = t38.*5.0e-1i;
t39 = -t37;
t41 = -t40;
t42 = t18+t19+t22+t23+t37+t40+1.0./2.0e+1;
t43 = abs(t42);
t44 = t17+t20+t21+t24+t39+t41-1.0./2.0e+1;
t45 = angle(t44);
t46 = 1.0./t43;
t47 = t10+t45;
out1 = t2./1.6e+1+t3./1.6e+1-t34./2.0+cos(t47).*(1.1e+1./1.0e+2)-t46.*(t18+t19+t37+1.0./2.0e+1).*(2.0./2.5e+1);
if nargout > 1
    out2 = t4./1.6e+1+t5./1.6e+1-t36./2.0+sin(t47).*(1.1e+1./1.0e+2)-t46.*(t8.*(-1.0./1.6e+1)+t9./1.6e+1+t38./2.0).*(2.0./2.5e+1);
end
