function out1 = J_cartesian(thetaL,thetaR)
%J_cartesian
%    OUT1 = J_cartesian(thetaL,thetaR)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Dec-2022 13:32:21

t2 = cos(thetaL);
t3 = cos(thetaR);
t4 = sin(thetaL);
t5 = sin(thetaR);
t6 = t2./8.0;
t7 = t3./8.0;
t8 = t4./8.0;
t9 = t5./8.0;
t10 = -t6;
t11 = -t9;
t12 = t8+t11;
t14 = t7+t10+1.0./1.0e+1;
t13 = t12.^2;
t15 = (t2.*t12)./4.0;
t16 = (t3.*t12)./4.0;
t17 = t14.^2;
t18 = (t4.*t14)./4.0;
t19 = (t5.*t14)./4.0;
t20 = t13+t17;
t24 = t15+t18;
t25 = t16+t19;
t21 = 1.0./t20;
t22 = t21.^2;
t23 = t21./4.0;
t26 = t23-1.0;
t27 = sqrt(t26);
t28 = 1.0./t27;
out1 = reshape([real(t12.*t22.*t24.*t28)./1.6e+1-real(t2.*t27)./1.6e+1-real(t4)./1.6e+1,real(t14.*t22.*t24.*t28)./1.6e+1-real(t4.*t27)./1.6e+1+real(t2)./1.6e+1,real(t12.*t22.*t25.*t28).*(-1.0./1.6e+1)+real(t3.*t27)./1.6e+1-real(t5)./1.6e+1,real(t14.*t22.*t25.*t28).*(-1.0./1.6e+1)+real(t5.*t27)./1.6e+1+real(t3)./1.6e+1],[2,2]);
